name: gh-pages

on:
  push:
    branches: [dev, master]
  pull_request:
    branches: [dev, master]

jobs:
  create-and-publish-docs:
    name: Create Documentation
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pipx
        run: |
          python3 -m pip install pipx
      - name: Install poetry, nox
        run: |
          pipx install poetry
          pipx install nox
      - name: Install footings-idi-model
        run: |
          poetry install
      - name: Poetry show libraries
        run: |
          poetry show
      - name: Pip show footings-idi-model
        run: |
          poetry run pip show footings-idi-model
      - name: Run sphinx
        run:  nox -s create_docs
      - name: Deploy docs to github pages - master
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/_build
          destination_dir: ./master
      - name: Deploy docs to github pages - dev
        if: github.ref == 'refs/heads/dev'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/_build
          destination_dir: ./dev
